### ISSUE TITLE
Printed copies

### ISSUE THREAD

**Issue by neofright** [edhamma/vism#3]
I used to be happy reading on electronic devices such as Kindles, however at this stage in my life I find myself vastly preferring printed books for a number of reasons I won't detail now!

Do you have any experience with professional PDF printing methods that would allow me to have a paperback copy of the Visuddhimagga?

The only physical copy of Bhikkhu Ñāṇamoli's translation I can find to buy is a terribly beaten up copy for around $70 USD. That ought to be a sizeable budget for me to produce a PDF print.

I'm aware that as a question this is beyond the technical scope of this project, so feel free to close this issue.

Edit: After trying a bunch of websites myself to try and get this printed I decided to make an offer and won the copy on eBay for $55 USD.

**Comment by eudoxos** [comment]
Hi, good :) I just know print-on-demand lulu.com [which has Visuddhimagga](https://www.lulu.com/shop/bhaddantacariya-buddhaghosa/visuddhimagga/hardcover/product-1k89qn8z.html?q=visuddhimagga&page=1&pageSize=4) for $42 - probably print of the 2011 PDF. I find reading Visuddhimagga easier in digital — not on e-reader but on screen, since it is navigable; and the text is highly structured, so it does not read like a novel, start to end. At least not me :)

**Comment by neofright** [comment]
Thank you for the reply! Thanks also for this project. I will treat the searchable digital copy as a companion to my print edition.

I've emailed Lennart to ask him which translation he is using (a search of the ISBN provided nothing). I'll reply here if he confirms to me which version is on lulu.

**Comment by eudoxos** [comment]
LOL :))) Anyway, there is practically just one translation (besides PTS from 20s), that of Bhikkhu Ñanamoli from the 50s. All editions are reprints of that one, including the PDF prepared by Buddhist Publication Society in 2011. Good luck with Pali.

**Comment by neofright** [comment]
I used lulu.com and I thought you may be interested in how things went. It was cheaper than buying a vintage copy and is probably more readable in this textbook style format. I'm pleased.
```
Book, 620 Pages
Print Book: A4 (8.27 x 11.69 in / 210 x 297 mm)
Standard Black & White
60# White
Paperback
Matte Cover
Print Cost: USD 23.10
```

Some images are in this [imgur album](https://imgur.com/a/wdhocyK) e.g. 

![image](https://i.imgur.com/xrSjsiG.jpeg)

Sādhu Sādhu Sādhu

**Comment by eudoxos** [comment]
Wow, that's the first physical copy I see! Did not expect this will happen. And it is cheaper than I thought, $23 for 620 pages... Enjoy :)
